inherit_from:
  - .rubocop_airbnb.yml

AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/*'
    - 'config/environments/*'
    - 'config/application.rb'
    - 'config/initializers/*'
    - 'config/spring.rb'
    - 'lib/tasks/*'
    - 'vendor/**/*'
    - 'path/ruby'
    - 'spec/**/*'

Rails/FilePath:
  Exclude:
    - 'config/puma.rb'

Metrics/BlockLength:
  Exclude:
    - 'config/routes.rb'

Metrics/ClassLength:
  Exclude:
    - 'app/models/user.rb'

Metrics/AbcSize:
  Exclude:
   - 'app/controllers/users/registrations_controller.rb'
  Max: 25

MethodLength:
  Exclude:
   - 'app/controllers/users/registrations_controller.rb'
  Max: 15

LineLength:
  Max: 125

AsciiComments:
  Enabled: false

Documentation:
  Enabled: false

ClassAndModuleChildren:
  Enabled: false
